project_id = "nqhkuyapfakrmhgjh"

[functions.view-profile-with-token]
verify_jwt = false

[functions.process-payment-success]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = true

[functions.verify-paypal-webhook]
verify_jwt = false

[functions.receive-lab-result]
verify_jwt = false

[functions.notify-partner-application]
verify_jwt = false

[functions.submit-partner-application]
verify_jwt = false

[functions.calculate-nightly-commissions]
verify_jwt = false

[functions.monitor-workforce-validity]
verify_jwt = false

[functions.submit-survey]
verify_jwt = false
