project_id = "nqhkuyapfakrmhgjh"

[functions.view-profile-with-token]
verify_jwt = false

[functions.process-payment-success]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = true

[functions.verify-paypal-webhook]
verify_jwt = false

[functions.receive-lab-result]
verify_jwt = false

[functions.notify-partner-application]
verify_jwt = false

[functions.submit-partner-application]
verify_jwt = false

[functions.calculate-nightly-commissions]
verify_jwt = false

[functions.monitor-workforce-validity]
verify_jwt = false

[functions.submit-survey]
verify_jwt = false

[functions.log-social-embed]
verify_jwt = false

[functions.refill-wallet]
verify_jwt = true

[functions.process-wallet-refill]
verify_jwt = true

[functions.process-smart-split]
verify_jwt = true

[functions.distribute-venue-pool]
verify_jwt = false

[functions.notify-investment-status]
verify_jwt = false

[functions.refill-ghost-wallet]
verify_jwt = true

[functions.send-auth-email]
verify_jwt = false

[functions.verify-email]
verify_jwt = false

[functions.approve-access-request]
verify_jwt = false

[functions.notify-access-request]
verify_jwt = true

[functions.notify-signup-alert]
verify_jwt = false

[functions.validate-member]
verify_jwt = false

[functions.trigger-footprint-liveness]
verify_jwt = true

[functions.footprint-webhook]
verify_jwt = false

[functions.process-valid-payment]
verify_jwt = true

[functions.create-wallet-checkout]
verify_jwt = true

[functions.verify-wallet-funding]
verify_jwt = false

[functions.synth-audit]
verify_jwt = false
